package com.joymeter.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.joymeter.dao.UserActivity;
import com.joymeter.dao.SyncupActivity;
import com.joymeter.dao.SyncupAction;

import com.joymeter.dao.UserActivityDao;
import com.joymeter.dao.SyncupActivityDao;
import com.joymeter.dao.SyncupActionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userActivityDaoConfig;
    private final DaoConfig syncupActivityDaoConfig;
    private final DaoConfig syncupActionDaoConfig;

    private final UserActivityDao userActivityDao;
    private final SyncupActivityDao syncupActivityDao;
    private final SyncupActionDao syncupActionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userActivityDaoConfig = daoConfigMap.get(UserActivityDao.class).clone();
        userActivityDaoConfig.initIdentityScope(type);

        syncupActivityDaoConfig = daoConfigMap.get(SyncupActivityDao.class).clone();
        syncupActivityDaoConfig.initIdentityScope(type);

        syncupActionDaoConfig = daoConfigMap.get(SyncupActionDao.class).clone();
        syncupActionDaoConfig.initIdentityScope(type);

        userActivityDao = new UserActivityDao(userActivityDaoConfig, this);
        syncupActivityDao = new SyncupActivityDao(syncupActivityDaoConfig, this);
        syncupActionDao = new SyncupActionDao(syncupActionDaoConfig, this);

        registerDao(UserActivity.class, userActivityDao);
        registerDao(SyncupActivity.class, syncupActivityDao);
        registerDao(SyncupAction.class, syncupActionDao);
    }
    
    public void clear() {
        userActivityDaoConfig.getIdentityScope().clear();
        syncupActivityDaoConfig.getIdentityScope().clear();
        syncupActionDaoConfig.getIdentityScope().clear();
    }

    public UserActivityDao getUserActivityDao() {
        return userActivityDao;
    }

    public SyncupActivityDao getSyncupActivityDao() {
        return syncupActivityDao;
    }

    public SyncupActionDao getSyncupActionDao() {
        return syncupActionDao;
    }

}
